### ISSUE TITLE
IndexDB not being freed up when removing offline video from within webapp

### ISSUE THREAD

**Issue by kkalarickal** [GoogleChrome/kino#128]
## Bug Description

When user removes offline version of a video file that was previously downloaded, the indexDB is not being freed up. As a result, multiple download and removals causes the db usage to keep increasing.

## Expected Behaviour

When a video that was downloaded for offline viewing is removed, the corresponding memory must be freed up as well. The user is given a view into this via the "Storage used" statistics in the Manage Downloads page. It is seen that this statistic never decreases even when the downloaded video is removed.

## Steps to reproduce

1. Go to [https://web-dev-media.web.app/single-video/](https://web-dev-media.web.app/single-video/) and download video for offline viewing
2. Go to [Manage Downloads](https://web-dev-media.web.app/downloads/) page to see the downloaded video
3. note the amount of "Storage used"
4. Hover over and click on the check box next to the name of the video to get the "Remove offline version" icon.
5. Click this icon to remove the video
6. Wait for a moment so that the undo message goes away (this would allow user to undo the removal operation)
7. once again, note the amount of "Storage used" -- it remains the SAME !!
8. Go back to the [https://web-dev-media.web.app/single-video/](https://web-dev-media.web.app/single-video/) page and once again download video for offline viewing
9.  Go to [Manage Downloads](https://web-dev-media.web.app/downloads/) page to see the downloaded video
10. note the amount of "Storage used" has increased !!

## Screenshots

1. Manage downloads page after initial download of video for offline viewing. Note the storage used is 0.02GB
![image](https://user-images.githubusercontent.com/3719412/118267029-b85e3d80-b4bb-11eb-9cd2-d105016fcf41.png)

2. Manage downloads page after clicking the "Remove offline version" button or the "Delete all" button and waiting for a moment. Note that the storage remains the same 0.02GB 
![image](https://user-images.githubusercontent.com/3719412/118267190-f2c7da80-b4bb-11eb-94e7-34d8c5b4a214.png)

3. Manage downloads page after a second attempt at downloading the video for offline viewing. Note that the storage used has increased to 0.04GB
![image](https://user-images.githubusercontent.com/3719412/118267300-1ee35b80-b4bc-11eb-806a-21498315169b.png)

## Additional context

- Project version: ef13dc0
- Node version: n.a.
- OS: Win 10
- Browser: chrome-90.0.4430.212
- Device: n.a.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by dero** [comment]
I'm not able to reproduce this issue anymore and I believe it has been long fixed. Attaching a screencast showing how IDB storage is properly evacuated when videos are removed.

https://user-images.githubusercontent.com/433570/136195906-1a195c9a-504a-4937-81d6-6035bf6c2190.mp4

**Comment by dero** [comment]
Assigning to @derekherman – if you agree, please go ahead and close the issue.

**Comment by kkalarickal** [comment]
Confirmed that this is a not-reproducible issue.
