### ISSUE TITLE
Improve Lighthouse scores

### ISSUE THREAD

**Issue by rkochman** [GoogleChrome/kino#142]
## Feature description

The site should also serve as an example of a well-performing site, so investigate and make enhancements to get Lighthouse scores in the 90s.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by beaufortfrancois** [comment]
FYI Here's the current Lighthouse score:

![image](https://user-images.githubusercontent.com/634478/132657162-a983993b-3721-4b1c-8e01-0d01473bb41e.png)

**Comment by beaufortfrancois** [comment]
@derekherman @dero Do you know when latest merged changes will be visible on https://kinoweb.dev/?

**Comment by derekherman** [comment]
@beaufortfrancois They are currently only on staging. I need to create a release to deploy to production. I’ll work on it later today.

**Comment by beaufortfrancois** [comment]
Out of curiosity, what's the URL for staging?

**Comment by beaufortfrancois** [comment]
@derekherman Please let me know when it's deployed on production so that we can compare scores. Thank you!

**Comment by derekherman** [comment]
The latest has been deployed to production and the LH numbers are definitely improved.

**Comment by beaufortfrancois** [comment]
They are! Woohoo!

![image](https://user-images.githubusercontent.com/634478/134636604-7910e47c-ef62-442b-93ad-6f0581c2eb7c.png)

**Comment by rkochman** [comment]
That's awesome--thank you!

**Comment by derekherman** [comment]
Awesome work @beaufortfrancois thank you for all the enhancements. The scores look great!
