### ISSUE TITLE
Improve firebase init command in README.md file

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/kino#157]
README.md file says `firebase init` however it's not clear which firebase features to enable.
It would be better to have them listed properly as in `firebase init [feature_name_1] [feature_name_2]`.

**Comment by derekherman** [comment]
The project already has a `firebase.json`, so I would assume it reads the features from that file. If that is not the case then we could just change it to `firebase init hosting`, as Hosting is the only feature we need for this project.

**Comment by derekherman** [comment]
No, it is not intended that it would update the config file. What we want would be to initialize Firebase so it creates the `.firebaserc` but does not change the config file. The docs on that CLI command are very sparse.

**Comment by derekherman** [comment]
I think the option **Configure as a single-page app (rewrite all urls to /index.html)?** should be set to **Yes** and then it would leave the config file as-is.

**Comment by beaufortfrancois** [comment]
Thank you @derekherman! You're right.
Here's the PR: https://github.com/GoogleChrome/kino/pull/159
