### ISSUE TITLE
Stop first video when second video starts playing

### ISSUE THREAD

**Issue by felipebochehin87** [GoogleChrome/kino#184]
## Feature description

We currently allow two videos being played at the same time (one in PiP, another one in the regular view). I kindly suggest stopping the first video (even if this is in PiP) when the second video starts playing.
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Stop the first video (even if this is in PiP) when the second video starts playing.

## Implementation brief

* 

## QA testing instructions

1. Start playing a video
2. Move it to PiP
3. Go back to home
4. Start playing another video

## Demo

* 

## Changelog entry

*

**Comment by dero** [comment]
@felipebochehin87 I considered that during development – and I personally think the application should not presume the user only wants to watch one playing video at a time.

Two reasons for that:

1. I can think of many use cases for having two videos playing at the same time: one in PiP and the other on a page. Imagine there is a live broadcast of a soccer game. I'm waiting for a match to start, so I keep that stream playing muted in PiP and just check it from time to time while watching another video as my main content while I'm waiting.
2. For learning purposes, I think it's useful for any developers to be able to test out and see that PiP video can play alongside any other video on a web page.

**Comment by dero** [comment]
Chatted with @felipebochehin87 and we decided to close this issue.
